config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :time_logs
  resources :time_log_stopper, only: [:update]
  root to: 'time_logs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_log.rb
class TimeLog < ApplicationRecord
  belongs_to :user

  validate :correct_duration, on: :update

  def running?
    end_time.nil?
  end

  private

  def correct_duration
    return true if end_time.nil?

    if start_time > end_time
      errors.add(:end_time, 'End time must be after start time')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :time_logs
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/time_log_stopper_controller.rb
class TimeLogStopperController < ApplicationController
  before_action :set_time_log

  def update
    if @time_log.end_time.nil?
      @time_log.update(end_time: Time.now)
      redirect_to time_logs_path, notice: 'The timer has been stopped.'
    else
      redirect_to time_logs_path,
                  alert: "Could not end the timer."
    end
  end

  private
    def set_time_log
      @time_log = current_user.time_logs.find(params[:id])
    end
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
  before_action :set_time_log, only: [:show, :edit, :update, :destroy]

  def index
    @time_logs = current_user.time_logs.map { |l| TimeLogPresenter.new(l) }
  end

  def create
    @time_log = current_user.time_logs.new(start_time: DateTime.now)

    if @time_log.save
      redirect_to time_logs_path, notice: 'Your timer was started.'
    else
      render :index, alert: 'There was an error starting your timer.'
    end
  end

  def update
    if @time_log.update(time_log_params)
      redirect_to time_logs_path, notice: 'Time log was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @time_log.destroy
    redirect_to time_logs_url, notice: 'Time log was successfully destroyed.'
  end

  private
    def set_time_log
      @time_log = current_user.time_logs.find(params[:id])
    end

    def time_log_params
      params.require(:time_log).permit(:start_time, :end_time, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_logs_helper.rb
require 'time_difference'

module TimeLogsHelper
  def time_log_button
    current_log&.running? ? stop_timer : start_timer
  end

  def stop_timer
    link_to 'Stop Timer',
            time_log_stopper_path(current_log),
            method: :patch,
            class: :button

  end

  def start_timer
    link_to 'Start Timer', time_logs_path, method: :post, class: :button
  end

  private

  def current_log
    current_user.time_logs.last
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeClock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <ul>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </nav>

  <body>
    <p class="notice"<%= notice %></p>
    <p class="alert"<%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/time_logs/_form.html.erb
<%= form_with(model: time_log, local: true) do |form| %>
  <% if time_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_log.errors.count, "error") %> prohibited this time_log from being saved:</h2>

      <ul>
      <% time_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_logs/_time_log.erb
<tr>
  <td><%= time_log.date %></td>
  <td><%= time_log.start_time %></td>
  <td><%= time_log.end_time %></td>
  <td><%= time_log.duration %></td>
  <td><%= link_to 'Edit', edit_time_log_path(time_log) %></td>
  <td><%= link_to 'Destroy', time_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/time_logs/edit.html.erb
<h1>Editing Time Log</h1>

<%= render 'form', time_log: @time_log %>

<%= link_to 'Show', @time_log %> |
<%= link_to 'Back', time_logs_path %>

app/views/time_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Time Logs</h1>

<%= time_log_button %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @time_logs, cache: true %>
  </tbody>
</table>

<br>